### ISSUE TITLE
Error : object 'mccollect' is not exported by 'namespace:parallel'

### ISSUE THREAD

**Issue by dualvim** [rdpeng/threadpool#1]
Hi Roger,
I'm Trying to install the "threadpool" package here, but I'm having some trouble.
After I install the R Packages 'thor' and 'queue', I tried to install the 'threadpool' package but it returned the error 
`Error : object 'mccollect' is not exported by 'namespace:parallel'
ERROR: lazy loading failed for package 'threadpool'`

I'm trying to install it in Windows 10, with R 3.4.3. 

Your package looks promissing! I'm Really curious to check it out!

**Comment by rdpeng** [comment]
I think this may be a Windows issue as the mc* functions in the parallel package (I believe) do not work on Windows. They require the forking mechanism that only exists on Unix and Mac.

**Comment by dualvim** [comment]
It is a Windows issue... I figured it out this later reading the documentation of the "parallel" package, and after installing and testing it my Raspberry Pi. Thank you very much Mr. Peng!
